version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: localhost:5001/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - BACKEND_SVC=${BACKEND_SVC}
    image: localhost:5001/backend
    volumes:
      - "/home/spire/spiresplash/pki/certs/backend:/etc/nginx/certs"
    ports:
      - "${BACKEND_HOST_PORT}:443"