---
- name: Create spire user
  user:
    name: "{{ ansible_user }}"
    append: yes
    state: present
    createhome: yes
    shell: /bin/bash

- name: Allow sudo without password
  lineinfile:
    dest: /etc/sudoers
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Set up authorized keys for the spire user
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  with_file:
    - ~/.ssh/id_rsa.pub