- name: Install pre-requisites for docker
  apt:
    pkg:
      - software-properties-common
      - apt-transport-https
      - build-essential
      - python3-pip
      - python3-setuptools
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes

- name: Install pre-requisites for docker and k8s in python
  pip:
    name:
      - docker

- name: Add Docker signing key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add repository into sources list
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} edge"
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: "docker"
    append: yes

- name: Allow access to docker socket
  shell: "sudo setfacl -m user:{{ ansible_user }}:rw /var/run/docker.sock"

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "u+x,g+x"

- name: Change docker-compose permission
  file:
    path: /usr/local/bin/docker-compose
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

