apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: tornjak
      port: 10000
      targetPort: 10000
  selector:
    app: spire-server
